#!/usr/bin/python3

from sys import argv


def factorize(value):
    """"print a simple descomposition of an integer > 1"""
    i = 2

    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
    print(value, "<- value-aft")
    print()


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(value)
            except ValueError:
                print(f"Invalid value on line: {line}")
                line = file.readline()
            except FileNotFoundError:
                print(f"File '{argv[1]}' not found.")
                except Exception as e:
                    print(f"An unexpected error occurred: {e}")
                    pass
